export const COURSE_REPOSITORY_TOKEN = Symbol('COURSE_REPOSITORY');
export const USER_REPOSITORY_TOKEN = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY_TOKEN = Symbol('REFRESH_TOKEN_REPOSITORY');
